/**
 * PrivacyGuard — Detection Bundle Builder
 *
 * Concatenates the detection engine modules (constants, regexEngine,
 * injectionScanner, masker) into a single IIFE for use as a Chrome
 * content script. Strips ES module import/export statements and exposes
 * all public functions via window.__PrivacyGuard.
 *
 * Usage:
 *   node scripts/build.js
 *   npm run build
 *
 * Output:
 *   dist/detection.bundle.js
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

// ─── Source Files (order matters: constants first) ──────────────
const SOURCES = [
  'src/utils/constants.js',
  'src/detection/regexEngine.js',
  'src/detection/injectionScanner.js',
  'src/utils/masker.js',
  'src/utils/storage.js',
];

// ─── Build ─────────────────────────────────────────────────────

function stripModuleSyntax(code) {
  return code
    // Remove import statements (single and multi-line)
    .replace(/^import\s+\{[^}]*\}\s+from\s+['"][^'"]+['"];?\s*$/gm, '')
    .replace(/^import\s+.*from\s+['"][^'"]+['"];?\s*$/gm, '')
    // Remove export { ... } blocks
    .replace(/^export\s+\{[^}]*\};?\s*$/gm, '')
    // Strip 'export' from inline declarations (export const → const)
    .replace(/^export\s+(const|let|var|function|class)\s/gm, '$1 ');
}

function build() {
  const timestamp = new Date().toISOString();

  let bundle = '';
  bundle += `// PrivacyGuard Detection Bundle\n`;
  bundle += `// Auto-generated by scripts/build.js — DO NOT EDIT DIRECTLY\n`;
  bundle += `// Built: ${timestamp}\n`;
  bundle += `// Source modules: ${SOURCES.join(', ')}\n\n`;
  bundle += `(function () {\n`;
  bundle += `  'use strict';\n\n`;
  bundle += `  const __PG = (window.__PrivacyGuard = window.__PrivacyGuard || {});\n\n`;

  for (const file of SOURCES) {
    const fullPath = path.resolve(ROOT, file);
    let code = fs.readFileSync(fullPath, 'utf-8');

    // Strip ES module syntax
    code = stripModuleSyntax(code);

    // Indent all lines by 2 spaces for clean nesting inside IIFE
    const indented = code
      .split('\n')
      .map(line => (line.trim() ? '  ' + line : ''))
      .join('\n');

    bundle += `  // ${'═'.repeat(60)}\n`;
    bundle += `  // Source: ${file}\n`;
    bundle += `  // ${'═'.repeat(60)}\n\n`;
    bundle += indented;
    bundle += '\n\n';
  }

  // Expose public API on namespace
  bundle += `  // ${'═'.repeat(60)}\n`;
  bundle += `  // Public API — exposed on window.__PrivacyGuard\n`;
  bundle += `  // ${'═'.repeat(60)}\n`;
  bundle += `  __PG.CATEGORY = CATEGORY;\n`;
  bundle += `  __PG.SEVERITY = SEVERITY;\n`;
  bundle += `  __PG.SEVERITY_WEIGHT = SEVERITY_WEIGHT;\n`;
  bundle += `  __PG.STORAGE_KEYS = STORAGE_KEYS;\n`;
  bundle += `  __PG.RULES = RULES;\n`;
  bundle += `  __PG.INJECTION_PATTERNS = INJECTION_PATTERNS;\n`;
  bundle += `  __PG.scanForPII = scanForPII;\n`;
  bundle += `  __PG.scanForInjection = scanForInjection;\n`;
  bundle += `  __PG.maskValue = maskValue;\n`;
  bundle += `  __PG.maskAll = maskAll;\n`;
  bundle += `  // Storage API\n`;
  bundle += `  __PG.setEnabled = setEnabled;\n`;
  bundle += `  __PG.isEnabled = isEnabled;\n`;
  bundle += `  __PG.addToAllowlist = addToAllowlist;\n`;
  bundle += `  __PG.removeFromAllowlist = removeFromAllowlist;\n`;
  bundle += `  __PG.isAllowed = isAllowed;\n`;
  bundle += `  __PG.getAllowlist = getAllowlist;\n`;
  bundle += `  __PG.addDetection = addDetection;\n`;
  bundle += `  __PG.getDetections = getDetections;\n`;
  bundle += `  __PG.clearDetections = clearDetections;\n`;
  bundle += `  __PG.getDetectionCount = getDetectionCount;\n\n`;
  bundle += `})();\n`;

  // Write output
  const distDir = path.resolve(ROOT, 'dist');
  fs.mkdirSync(distDir, { recursive: true });

  const outPath = path.resolve(distDir, 'detection.bundle.js');
  fs.writeFileSync(outPath, bundle, 'utf-8');

  const sizeKB = (Buffer.byteLength(bundle) / 1024).toFixed(1);
  console.log(`✅ Built: dist/detection.bundle.js (${sizeKB} KB)`);
  console.log(`   Sources: ${SOURCES.length} modules`);
}

build();
